services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 129:3000
    environment:
      REACT_APP_API: ${REACT_APP_API}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
      REACT_APP_OPEN_WEATHER_API_KEY: ${REACT_APP_OPEN_WEATHER_API_KEY}
